apiVersion: v1
kind: Service
metadata:
  name: i27-ticket
  labels:
    app: i27-ticket
spec:
  type: ClusterIP
  selector:
    app: i27-ticket
  ports:
    - name: http
      port: 80
      targetPort: 8082
